[tool.tox]
legacy_tox_ini = """
    [tox]
    envlist =
        py311
    skipsdist = True

    [testenv:py311]
    deps =
        -r requirements.txt
    commands =
        pytest \
        --html=test-reports/report.html \
        --self-contained-html \
        -s \
        -v \
        --cov=src \
        --cov-report=xml:test-reports/coverage.xml \
        --cov-branch \
        --junitxml=test-reports/unittests.xml \
        --log-file=test-reports/logs.txt \
        tests
"""

[tool.coverage.run]
relative_files = true
source = ["src/syn_service"]
branch = true

[tool.coverage.report]
fail_under = 100
show_missing = true
skip_empty = true

[tool.flake8]
max-line-length = 100
