[tool.tox]
legacy_tox_ini = """
    [tox]
    envlist =
        py311
        docs
        lint
    skipsdist = True

    [testenv]
    deps =
        -r requirements.txt
    commands =
        coverage run -m pytest -v -s --html=report.html tests/
        coverage report
        mypy src

    [testenv:type]
    deps = mypy
    commands = mypy src

    [docs]
    deps =
        -r requirements.txt
    commands =
        sphinx-apidoc -e -f -o source/ ../src
        make html

    [lint]
    deps =
        flake8
    commands =
        flake8 src
"""

[tool.coverage.run]
relative_files = true
source = ["src/syn_service"]
branch = true

[tool.coverage.report]
fail_under = 100
show_missing = true
skip_empty = true

[tool.flake8]
max-line-length = 100
