[tool.tox]
legacy_tox_ini = """
    [tox]
    envlist =
        py311
        documentation
    skipsdist = True

    [testenv:py311]
    deps =
        -r requirements.txt
    commands =
        pytest \
        --self-contained-html \
        -s \
        -v \
        --cov=src \
        --cov-report=xml:test-reports/coverage.xml \
        --cov-branch \
        --cov-fail-under=50 \
        --junitxml=test-reports/junit.xml \
        tests

    [testenv:documentation]
    basepython = python3
    skip_install = true
    allowlist_externals = make
    changedir = docs
    deps =
        sphinx
        sphinx-rtd-theme
    commands =
        make html

"""

[tool.coverage.run]
relative_files = true
source = ["src/syn_service"]
branch = true

[tool.coverage.report]
fail_under = 0
show_missing = true
skip_empty = true

[tool.flake8]
max-line-length = 100
