default:
  image: python:3.11-alpine

stages:
  - test
  - build
  - deploy

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  IMAGE_NAME: leewx/syn-template
  IMAGE_TAG: syn-template-1.0

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip

before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

run_tests:
  stage: test
  script:
    - pip install tox  # you can also use tox
    - tox -p

build_image:
  stage: build
  image: docker:26.0.0
  services:
    - docker:26.0.0-dind
  variables: 
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG -f cicd/dockerfile/Dockerfile.api .
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  image: ruby:3.3.0
  before_script:
    - chmod 400 $DIGITAL_OCEAN_SSH
  script:
    - ssh -o StrictHostKeyChecking=no -i $DIGITAL_OCEAN_SSH root@128.199.123.104
      "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD &&
      docker pull $IMAGE_NAME:$IMAGE_TAG &&
      docker container rm -f my-app || true &&
      docker run -d -p 5000:5000 --name my-app $IMAGE_NAME:$IMAGE_TAG"
