version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - pip install --upgrade pip
      - pip install .
      - mkdir test-reports
      - pip install tox
  build:
    commands:
      - tox
  post_build:
    commands:
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING -ne 0 ]; then
          CODE_COMMENT='BUILD FAILED'
          PR_STATUS='REVOKE'
        else
          CODE_COMMENT='BUILD SUCCESS'
          PR_STATUS='APPROVE'
        fi
      - aws codecommit post-comment-for-pull-request --pull-request-id $pullRequestId --repository-name $repositoryName --content "${CODE_COMMENT} - ${CODEBUILD_LOG_PATH}" --before-commit-id $destinationCommit --after-commit-id $sourceCommit --region $AWS_DEFAULT_REGION
      - REVISION_ID=$(aws codecommit get-pull-request --pull-request-id $pullRequestId --region $AWS_DEFAULT_REGION | jq -r '.pullRequest.revisionId')
      - aws codecommit update-pull-request-approval-state --pull-request-id $pullRequestId --revision-id $REVISION_ID --approval-state $PR_STATUS --region $AWS_DEFAULT_REGION
      - echo Build completed on `date`

reports:
  coverage_tests:
    files:
      - 'coverage.xml'
    base-directory: 'test-reports'
    file-format: COBERTURAXML
  report:
    files:
      - 'junit.xml'
    base-directory: 'test-reports'
    discard-paths: yes
    file-format: JunitXml