version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - pip install --upgrade pip
      - pip install .
      - mkdir test-reports
      - pip install tox
  build:
    commands:
      - tox
  post_build:
    commands:
      - echo Build completed on `date`

reports:
  unit_tests:
    files:
      - unittests.xml
    file-format: JUNITXML
  coverage_tests:
    files:
      - coverage.xml
    file-format: COBERTURAXML