FROM public.ecr.aws/docker/library/python:3.11.8-alpine3.18

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./src /code/src

CMD ["uvicorn", "src.main:ApiClient", "--proxy-headers", "--host", "0.0.0.0", "--port", "5000"]
